name: Node.js Service Container Example

on: workflow_dispatch

jobs:
  run-node:
    runs-on: ubuntu-latest

    services:
      node:
        image: node:20
        volumes:
          - ${{ github.workspace }}:/home/node/app
        options: --name node
        ports:
          - 3000:3000

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Restart Node after checkout
      # Restart MQTT after volumes have been checked out
      uses: docker://docker
      with:
        args: docker restart node

    - name: Setup node locally
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run a script using Node.js
      run: |
        docker exec -d node node index.js
        sleep 5
        curl "http://localhost:3000"
        echo "done"