name: Node.js Service Container Example

on: workflow_dispatch

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup node locally
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run background service
      run: docker run -p 3000:3000 -d --workdir /home/node/app -v ${{ github.workspace }}:/home/node/app node:20-alpine node index.js

    - name: Run a script using Node.js
      run: |
        curl "http://localhost:3000"
        echo "done"